### ISSUE TITLE
Issue with _safemint call for preexisting currentId

### ISSUE THREAD

**Issue by karuu23** [mouse-dev-1/Akutar#9]
Is there a scenario where we would call airdrop API multiple times for same airdropGrouping ?
If we do it, then currentId could be calculated to same value over multiple calls .
If that happens, minting would fail for some addresses.
We currently dont have any data structure that identifies if an address has already minted or not.

**Comment by wyecompany** [comment]
yes it's possible the same group may be airdropped multiple times when the group is particularly large, however the increment of airdropGroupings[airdropGrouping].minted at the end could be used to prevent a group from over-minting

Propose it is moved up to so that it is incremented immediately before currentId is set to avoid self-caused re-entrancy issues

**Comment by wyecompany** [comment]
Changed to _mint
